version: '3.8'

services:
  backend:
    image: ghcr.io/dangdat204/to-do-app:latest
    container_name: task-app-backend
    restart: always
    ports:
      - "4000:4000"
    networks:
      - app-network

  frontend:
    # build:
    #   context: .
    image: ghcr.io/doanhvanvu82/todo-app:latest
    container_name: task-app-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
